spring.application.name=HipotecarioPLD
logging.level.root=info
logging.file.name=/opt/jboss/wildfly/standalone/log/HipotecarioPLD.log
logging.structured.format.file=com.bancoppel.HipotecarioPLD.log.MyStructuredLoggingFormatter
############################
#         Filtros          #
############################
cors.allowed-origins=http://127.0.0.1:5500,http://localhost:4200,http://localhost:3000
cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
cors.allowed-headers=Authorization,Cache-Control,Content-Type,Accept
cors.max-age=3600
##################################################################################################
# 1. Target the BigQuery Client RPC
# This may show high-level steps within the library
#logging.level.com.google.cloud.bigquery=DEBUG

# 2. Target the Google HTTP Client components
# This is crucial for seeing the actual HTTP interaction details
#logging.level.com.google.api.client.http.apache=DEBUG
#logging.level.com.google.api.client.http=DEBUG

# 3. Target the underlying Apache HTTP client (if used by the transport)
# This provides granular wire-level details (headers, body, etc.)
#logging.level.org.apache.http=DEBUG
##################################################################################################
spring.config.import=aws-parameterstore:/hipotecario/kubernetes/validaciones/
spring.cloud.aws.region.static=us-east-1
#logging.level.io.awspring.cloud=DEBUG
#logging.level.software.amazon.awssdk=DEBUG
server.port=8082
